name: Build/release

on:
  workflow_dispatch:
    inputs:
      build_components:
        description: Build components
        required: true
        default: All
        type: choice
        options:
          - All
          - driver
          - tool
          - capture-server

      build_configuration:
        description: Build configuration
        required: true
        default: Debug
        type: choice
        options:
          - Debug
          - Release

      create_release:
        description: Create GitHub release
        required: true
        default: false
        type: boolean
   
jobs:
  build:
    name: Build ${{ inputs.build_components }} (${{ inputs.build_configuration }})
    runs-on: windows-2022
    permissions:
        contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Build driver
        uses: ./.github/actions/build_driver
        if: ${{ inputs.build_components == 'All' || inputs.build_components == 'driver' }}
        with:
          solution: .\cxadc-win.sln
          configuration: ${{ inputs.build_configuration }}
          platform: x64

      - name: Build tool
        uses: ./.github/actions/build_tool
        if: ${{ inputs.build_components == 'All' || inputs.build_components == 'tool' }}
        with:
          configuration: ${{ inputs.build_configuration }}
          framework: net8.0-windows
          runtime: win-x64

      - name: Build capture-server
        uses: ./.github/actions/build_capture_server
        if: ${{ inputs.build_components == 'All' || inputs.build_components == 'capture-server' }}
        with:
          solution: .\cxadc-win.sln
          configuration: ${{ inputs.build_configuration }}
          platform: x64

      - name: Download all artifacts (bin)
        uses: actions/download-artifact@v4
        if: ${{ inputs.create_release }}
        with:
          path: bin
          pattern: bin-*
          merge-multiple: true

      - name: Download all artifacts (pdb)
        uses: actions/download-artifact@v4
        if: ${{ inputs.create_release }}
        with:
          path: pdb
          pattern: pdb-*
          merge-multiple: true

      - name: Create GitHub Release
        if: ${{ inputs.create_release }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: pwsh
        run: |
          gh release create '${{ github.ref_name }}' --title '${{ github.ref_name }}' --draft

          Compress-Archive -DestinationPath cxadc-win-x64.zip -Path bin/*
          gh release upload '${{ github.ref_name }}' 'cxadc-win-x64.zip#cxadc-win-${{ github.ref_name }}-x64.zip'

          Compress-Archive -DestinationPath cxadc-win-x64-pdb.zip -Path pdb/*
          gh release upload '${{ github.ref_name }}' 'cxadc-win-x64-pdb.zip#cxadc-win-${{ github.ref_name }}-x64-pdb.zip'

