name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      # Optional: install Windows SDK components if your driver project requires them.
      # Uncomment this block if the build later fails due to missing SDK headers/libraries.
      #
      # - name: Ensure Visual Studio Windows SDK components
      #   shell: cmd
      #   run: |
      #     "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" --quiet --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --add Microsoft.VisualStudio.Component.Windows10SDK.19041 --wait

      - name: Build solution (driver, Release x64)
        shell: cmd
        run: >-
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
          .\cxadc-win.sln
          /t:driver
          /p:Configuration=Release
          /p:Platform=x64
          /v:detailed
